# -*- coding: utf-8 -*-
"""Build the Cardiovascular Diabetology "Research Insights" table, and enforce its limits.

CVD, verbatim from the Research-article guidelines: authors are encouraged to add a Research
Insights summary of under 200 words below the abstract, answering four set questions --

    What is currently known about this topic?            (max. 3 highlights)
    What is the key research question?                   (formatted as a question)
    What is new?                                         (max. 3 highlights)
    How might this study influence clinical practice?    (max. 1 highlight)

-- where "each highlight should be no more than 100 characters including spaces and punctuation",
and the whole thing is uploaded as a table.

Every limit is asserted here rather than counted by eye: the character budget is tight enough that a
one-word edit can breach it, and a breach is invisible in a rendered table.
"""
# --- portable roots -----------------------------------------------------------------------------
# Injected by scripts/build_repo.py. The working tree hardcoded an absolute local path; the deposit
# resolves it from CKM_P4_BASE, or from this file's own location (repo/code/ plays the role the
# working tree called independent_build/). Raw GWAS summary statistics are NOT deposited: set
# CKM_ROOT to wherever you obtained them if you intend to re-run the upstream extraction steps.
import os as _os
P4_BASE = _os.environ.get("CKM_P4_BASE") or _os.path.dirname(
    _os.path.dirname(_os.path.abspath(__file__)))
P4_ROOT = _os.environ.get("CKM_P4_ROOT") or _os.path.dirname(P4_BASE)
CKM_ROOT = _os.environ.get("CKM_ROOT") or _os.path.dirname(P4_ROOT)
SHARED_LIB = _os.environ.get("CKM_SHARED_LIB") or _os.path.join(CKM_ROOT, "_shared")
# ------------------------------------------------------------------------------------------------

import io, os, re, sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

BASE = P4_BASE
FIG = os.path.join(BASE, "figures")

CHAR_LIMIT = 100
WORD_LIMIT = 200

SECTIONS = [
    ("What is currently known about this topic?", 3, [
        "AHA CKM staging places adiposity and dysglycaemia in earlier clinical stages of CVD.",
        "That ordering rests on observational data, where confounding is hard to exclude.",
        "CAD-independent adiposity effects on heart failure are already reported (HERMES, 2020).",
    ]),
    ("What is the key research question?", 1, [
        "Does CKM stage ordering hold genetically, and does adiposity act beyond CAD in heart failure?",
    ]),
    ("What is new?", 3, [
        "All 132 directed edges among 12 CKM traits were estimated bidirectionally in Europeans.",
        "It quantifies that split: about 80% of the BMI-heart-failure effect bypasses CAD.",
        "Stage concordance beat a label permutation but NOT a degree-preserving null.",
    ]),
    ("How might this study influence clinical practice?", 1, [
        "Supports adiposity-directed, not glycaemia-directed, heart-failure prevention research.",
    ]),
]

problems = []
for question, maxn, highlights in SECTIONS:
    if len(highlights) > maxn:
        problems.append(f"{question!r}: {len(highlights)} highlights, limit {maxn}")
    for h in highlights:
        if len(h) > CHAR_LIMIT:
            problems.append(f"highlight is {len(h)} chars (limit {CHAR_LIMIT}): {h!r}")
q = SECTIONS[1][2][0]
if not q.rstrip().endswith("?"):
    problems.append("the key research question is not formatted as a question")

# The journal asks for HIGHLIGHTS, not prose. Concatenating them into one cell kept every highlight
# under 100 characters while shipping a 265-character paragraph, which is exactly what the format
# rule exists to prevent. Each highlight is now its own bulleted line inside the cell.
rows = ["| Question | Highlights |", "|---|---|"]
for question, _maxn, highlights in SECTIONS:
    bullets = "<br>".join(f"• {h}" for h in highlights)
    rows.append(f"| **{question}** | {bullets} |")
table = "\n".join(rows)

words = len(re.sub(r"(<br>|[|*#•-])", " ", table).split())
if words >= WORD_LIMIT:
    problems.append(f"table is {words} words, limit is under {WORD_LIMIT}")

out = [
    "<!-- CKM Paper 4 — Research Insights. GENERATED by scripts/build_research_insights.py, which",
    "enforces the Cardiovascular Diabetology limits: under 200 words overall, at most 3 highlights per",
    "question (1 for clinical practice), and at most 100 characters per highlight INCLUDING spaces and",
    "punctuation. Edit the SECTIONS list in that script, not this file. -->",
    "",
    "# Research Insights",
    "",
    table,
    "",
]
open(os.path.join(FIG, "RESEARCH_INSIGHTS.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")

print(f"total words: {words} (limit under {WORD_LIMIT})")
for question, _m, hs in SECTIONS:
    print(f"  {question}")
    for h in hs:
        print(f"    [{len(h):3d}/{CHAR_LIMIT}] {h}")
if problems:
    print(f"\n===== RESEARCH INSIGHTS FAILED — {len(problems)} problem(s) =====")
    for p in problems:
        print("  x", p)
    sys.exit(1)
print("\n===== RESEARCH INSIGHTS WITHIN ALL CVD LIMITS =====")
