# --- portable roots -----------------------------------------------------------------------------
# Injected by scripts/build_repo.py; see the note in the Python header. Set CKM_P4_BASE to override.
P4_BASE <- Sys.getenv("CKM_P4_BASE")
if (!nzchar(P4_BASE)) {
  .args <- commandArgs(trailingOnly = FALSE)
  .self <- sub("^--file=", "", .args[grep("^--file=", .args)])
  .here <- if (length(.self)) dirname(.self[1]) else "."
  P4_BASE <- normalizePath(file.path(.here, ".."), winslash = "/", mustWork = FALSE)
}
P4_ROOT <- Sys.getenv("CKM_P4_ROOT"); if (!nzchar(P4_ROOT)) P4_ROOT <- dirname(P4_BASE)
CKM_ROOT <- Sys.getenv("CKM_ROOT");   if (!nzchar(CKM_ROOT)) CKM_ROOT <- dirname(P4_ROOT)
SHARED_LIB <- Sys.getenv("CKM_SHARED_LIB")
if (!nzchar(SHARED_LIB)) SHARED_LIB <- file.path(CKM_ROOT, "_shared")
# ------------------------------------------------------------------------------------------------
# SupplFig6 — AHA-staging concordance vs a label-permutation null (EUR + 3-cohort panel).
# Source: figures/suppfig_data/suppfig6_null_*.csv + suppfig6_observed.csv
#         (generated by figures/suppfig6_staging_null.py, a non-destructive copy of scripts/07_staging.py:
#          same STAGE map, Bonferroni+Steiger DAG, seed 12345, 10,000 label permutations).
source(file.path(P4_BASE, "figures", "fig_setup.R"))

DD  <- file.path(FIG, "suppfig_data")
obs <- read.csv(file.path(DD, "suppfig6_observed.csv"), stringsAsFactors=FALSE)
nEUR  <- read.csv(file.path(DD, "suppfig6_null_EUR.csv"))
nBBJ  <- read.csv(file.path(DD, "suppfig6_null_BBJ.csv"))
nTPMI <- read.csv(file.path(DD, "suppfig6_null_TPMI.csv"))

gv <- function(coh, col) obs[obs$cohort==coh, col][1]

# ---------- 6a. EUR primary null (main requirement) ----------
oE <- gv("EUR","concordance"); pE <- gv("EUR","perm_p")
pa <- ggplot(data.frame(concordance=nEUR$concordance), aes(concordance)) +
  geom_histogram(bins=40, fill="grey80", colour="white", linewidth=0.15) +
  geom_vline(xintercept=oE, colour=POS_COL, linewidth=0.7) +
  annotate("text", x=oE-0.02, y=Inf, label=sprintf("observed = %.3f\nP = %.1e", oE, pE),
           colour=POS_COL, hjust=1, vjust=1.4, size=FS/.pt-0.5, lineheight=0.95) +
  annotate("text", x=0.40, y=Inf, label="label-permutation null\n(10,000 shuffles, EUR)",
           colour="grey35", hjust=0.5, vjust=1.4, size=FS/.pt-0.7, lineheight=0.95) +
  labs(x="Cross-stage concordance", y="Permutations",
       title="EUR staging order beats chance (P = 1.8e-3)") +
  coord_cartesian(xlim=c(0.15, 1.02)) + theme_ckm()

# ---------- 6b. three-cohort observed vs their own nulls ----------
nulls <- rbind(
  data.frame(cohort="EUR",  concordance=nEUR$concordance),
  data.frame(cohort="BBJ",  concordance=nBBJ$concordance),
  data.frame(cohort="TPMI", concordance=nTPMI$concordance))
nulls$cohort <- factor(nulls$cohort, levels=c("EUR","BBJ","TPMI"))
obs$cohort   <- factor(obs$cohort,   levels=c("EUR","BBJ","TPMI"))
obs$lab <- sprintf("obs=%.3f\nP=%.3f", obs$concordance, obs$perm_p)
obs$sig <- obs$perm_p < 0.05
COH3 <- c(EUR=COHORT_COL[["EUR"]], BBJ=COHORT_COL[["BBJ"]], TPMI=COHORT_COL[["TPMI"]])

pb <- ggplot(nulls, aes(concordance)) +
  geom_histogram(aes(y=after_stat(density)), bins=34, fill="grey82", colour="white", linewidth=0.12) +
  geom_vline(data=obs, aes(xintercept=concordance, colour=cohort), linewidth=0.7) +
  geom_text(data=obs, aes(x=ifelse(concordance>0.6, concordance-0.02, concordance+0.02), y=Inf, label=lab, colour=cohort),
            hjust=ifelse(obs$concordance>0.6,1,0), vjust=1.3, size=FS/.pt-1.2, lineheight=0.9, show.legend=FALSE) +
  facet_wrap(~cohort, ncol=1, strip.position="right") +
  scale_colour_manual(values=COH3, guide="none") +
  labs(x="Cross-stage concordance", y="Null density",
       title="Only EUR is significant; EAS cohorts non-falsified (power-limited)") +
  coord_cartesian(xlim=c(0.1, 1.04)) + theme_ckm() +
  theme(strip.text.y=element_text(angle=0))

sf6 <- (pa | pb) + plot_layout(widths=c(1, 1)) +
  plot_annotation(tag_levels="a", theme=theme(plot.tag=element_text(size=FS_TAG, face="bold")))
save_fig(sf6, "SupplFig6", 178, 96)
cat(sprintf("SF6 done: EUR %.3f/P=%.4f  BBJ %.3f/P=%.4f  TPMI %.3f/P=%.4f\n",
    gv("EUR","concordance"),gv("EUR","perm_p"), gv("BBJ","concordance"),gv("BBJ","perm_p"),
    gv("TPMI","concordance"),gv("TPMI","perm_p")))
