# --- portable roots -----------------------------------------------------------------------------
# Injected by scripts/build_repo.py; see the note in the Python header. Set CKM_P4_BASE to override.
P4_BASE <- Sys.getenv("CKM_P4_BASE")
if (!nzchar(P4_BASE)) {
  .args <- commandArgs(trailingOnly = FALSE)
  .self <- sub("^--file=", "", .args[grep("^--file=", .args)])
  .here <- if (length(.self)) dirname(.self[1]) else "."
  P4_BASE <- normalizePath(file.path(.here, ".."), winslash = "/", mustWork = FALSE)
}
P4_ROOT <- Sys.getenv("CKM_P4_ROOT"); if (!nzchar(P4_ROOT)) P4_ROOT <- dirname(P4_BASE)
CKM_ROOT <- Sys.getenv("CKM_ROOT");   if (!nzchar(CKM_ROOT)) CKM_ROOT <- dirname(P4_ROOT)
SHARED_LIB <- Sys.getenv("CKM_SHARED_LIB")
if (!nzchar(SHARED_LIB)) SHARED_LIB <- file.path(CKM_ROOT, "_shared")
# ------------------------------------------------------------------------------------------------
# SupplFig4 — Leave-one-out sensitivity: no single variant drives the headline edges.
# Edges: CAD->HF, BMI->CAD, LDL->CAD, BMI->T2D. Same pipeline inputs as SF3
# (data/instruments/<EXP>.clumped.tsv + data/harmonised/<EXP>__<OUT>.outcome.tsv, harmonise action=2).
# TwoSampleMR::mr_leaveoneout(): each point = IVW estimate with one SNP removed; dashed line = full IVW ("All").
# LOO table is READ from results/leaveoneout_headline.csv (generated by scripts/56_leaveoneout_headline.R).
source(file.path(P4_BASE, "figures", "fig_setup.R"))
suppressMessages(library(TwoSampleMR))
INSTR <- file.path(BASE,"data/instruments"); HARM <- file.path(BASE,"data/harmonised")

fmt_exp <- function(f) format_data(read.delim(f, stringsAsFactors=FALSE), type="exposure",
  snp_col="SNP", beta_col="beta", se_col="se", effect_allele_col="effect_allele",
  other_allele_col="other_allele", eaf_col="eaf", pval_col="pval", samplesize_col="N", phenotype_col="Phenotype")
fmt_out <- function(f) format_data(read.delim(f, stringsAsFactors=FALSE), type="outcome",
  snp_col="SNP", beta_col="beta", se_col="se", effect_allele_col="effect_allele",
  other_allele_col="other_allele", eaf_col="eaf", pval_col="pval", samplesize_col="N", phenotype_col="Phenotype")

EDGES <- list(c("CAD","HF"), c("BMI","CAD"), c("LDL","CAD"), c("BMI","T2D"))
# DERIVE from the committed edge table (was hardcoded 0.05/111, the superseded denominator).
BONF  <- 0.05/nrow(read.csv(file.path(RES, "forward_local_edges.csv")))
# ---- READ the committed leave-one-out table; do NOT recompute or re-write it. -----------------
# scripts/56_leaveoneout_headline.R is the authoritative generator. This script used to run
# mr_leaveoneout() itself and write results/leaveoneout_headline.csv, so the shipped file depended
# on which of the two ran last -- the same duplicate-writer defect fixed for MR-PRESSO (10_harden.R
# vs 10b_mrpresso.R). The figure now renders the committed table and nothing else.
LOOALL <- read.csv(file.path(RES, "leaveoneout_headline.csv"), stringsAsFactors = FALSE)
stopifnot(nrow(LOOALL) > 0, all(c("edge","SNP","b","se","p") %in% names(LOOALL)))
plotD <- list(); allref <- list(); report <- list()
for (ed in EDGES) {
  exp <- ed[1]; out <- ed[2]; tag <- sprintf("%s -> %s", exp, out)
  loo <- LOOALL[LOOALL$edge == tag, ]
  stopifnot(nrow(loo) > 1, any(loo$SNP == "All"))
  allrow <- loo[loo$SNP=="All", ]
  b_all <- allrow$b[1]; se_all <- allrow$se[1]
  sub <- loo[loo$SNP!="All", ]
  sub$rank <- rank(sub$b, ties.method="first")
  plotD[[tag]] <- sub
  allref[[tag]] <- data.frame(edge=tag, b=b_all, lo=b_all-1.96*se_all, hi=b_all+1.96*se_all, n=nrow(sub))
  # influence diagnostics
  sub$dev <- sub$b - b_all
  imax <- sub[which.max(abs(sub$dev)), ]
  maxp <- max(sub$p)
  report[[tag]] <- sprintf("%-12s All b=%+.4f  LOO range [%+.4f, %+.4f]  max|dev|=%.4f (drop %s -> b=%+.4f)  max LOO p=%.2e  %s",
                           tag, b_all, min(sub$b), max(sub$b), max(abs(sub$dev)),
                           imax$SNP, imax$b, maxp,
                           ifelse(maxp<BONF, "ALL pass Bonferroni", "**some LOO NS at Bonferroni**"))
}
cat("== Leave-one-out influence report ==\n"); for (s in report) cat(s, "\n")

pD  <- do.call(rbind, plotD); aR <- do.call(rbind, allref)
lev <- sapply(EDGES, function(x) sprintf("%s -> %s", x[1], x[2]))
# `tag`/`lev` stay ASCII because they key into results/leaveoneout_headline.csv; the strip is typeset.
pD$edge <- factor(pD$edge, levels=lev, labels=disp_edge(lev))
aR$edge <- factor(aR$edge, levels=lev, labels=disp_edge(lev))

sf4 <- ggplot(pD, aes(b, rank)) +
  geom_rect(data=aR, inherit.aes=FALSE, aes(xmin=lo, xmax=hi, ymin=-Inf, ymax=Inf),
            fill="#B2182B", alpha=0.10) +
  geom_vline(data=aR, aes(xintercept=b), colour="#B2182B", linewidth=0.6, linetype="22") +
  geom_point(size=0.5, colour="grey30", alpha=0.6) +
  geom_text(data=aR, aes(x=b, y=Inf, label=sprintf("All IVW = %.3f\n(n=%d SNPs)", b, n)),
            colour="#B2182B", hjust=0.5, vjust=1.4, size=FS/.pt-1.1, lineheight=0.9, inherit.aes=FALSE) +
  facet_wrap(~edge, scales="free", nrow=2) +
  labs(x="Leave-one-out IVW estimate (one SNP removed)", y="Rank of leave-one-out estimate",
       title="Ranked leave-one-out estimates stay inside the full-instrument 95% CI (band)") +
  theme_ckm(legend="none")

save_fig(sf4, "SupplFig4", 178, 130)
cat("SF4 done; rendered from results/leaveoneout_headline.csv (", nrow(LOOALL), "rows read )\n")
